version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=storefront
      - POSTGRES_PASSWORD=storefront
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres:
